name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Restore node_modules cache
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: node_modules
          key: trusted-hint-controller${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Cache node modules
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: node_modules
          key: trusted-hint-controller${{ hashFiles('package-lock.json') }}
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Unpack node_modules
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: node_modules
          key: trusted-hint-controller${{ hashFiles('package-lock.json') }}
      - name: Build
        run: npm run build
  unit_test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Unpack node_modules
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: node_modules
          key: trusted-hint-controller${{ hashFiles('package-lock.json') }}
      - name: Unit Test
        run: npm run test
  integration_test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
      - name: Unpack node_modules
        uses: actions/cache/restore@v3
        id: cache
        with:
          path: node_modules
          key: trusted-hint-controller${{ hashFiles('package-lock.json') }}
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Integration Test
        run: npm run test:integration
        env:
          VITE_ANVIL_FORK_URL: ${{ secrets.VITE_ANVIL_FORK_URL }}
          VITE_ANVIL_BLOCK_NUMBER: ${{ secrets.VITE_ANVIL_BLOCK_NUMBER }}